// LUMINO product catalog — used by the WhatsApp webhook for search & matching
// Mirrors window.PRODUCTS in lumino.html (essential fields only)
module.exports = [
  {id:"prod_001",name:"Silk Wrap Midi Dress",brand:"& Other Stories",category:"women",subcategory:"dresses",price:189.99,sizes:["XS","S","M","L","XL"],colors:["Ivory","Black","Blush"],discount:null},
  {id:"prod_002",name:"Floral Chiffon Maxi Dress",brand:"Mango",category:"women",subcategory:"dresses",price:129.99,sizes:["XS","S","M","L","XL"],colors:["Floral Multi","Navy","Sage"],discount:null},
  {id:"prod_003",name:"Ribbed Cropped Top",brand:"COS",category:"women",subcategory:"tops",price:49.99,sizes:["XS","S","M","L","XL"],colors:["Ecru","Black","Taupe"],discount:null},
  {id:"prod_004",name:"Oversized Linen Blouse",brand:"Arket",category:"women",subcategory:"blouses",price:89.99,sizes:["XS","S","M","L","XL"],colors:["White","Dusty Blue","Terracotta"],discount:null},
  {id:"prod_005",name:"Wide-Leg Crepe Trousers",brand:"Reiss",category:"women",subcategory:"trousers",price:149.99,sizes:["6","8","10","12","14","16"],colors:["Black","Stone","Burgundy"],discount:null},
  {id:"prod_006",name:"Pleated Satin Midi Skirt",brand:"Whistles",category:"women",subcategory:"skirts",price:119.99,sizes:["XS","S","M","L","XL"],colors:["Champagne","Midnight","Blush"],discount:null},
  {id:"prod_007",name:"Linen-Blend Utility Jumpsuit",brand:"Zara",category:"women",subcategory:"jumpsuits",price:99.99,sizes:["XS","S","M","L","XL"],colors:["Khaki","White","Black"],discount:null},
  {id:"prod_008",name:"Wool-Blend Oversized Coat",brand:"Massimo Dutti",category:"women",subcategory:"coats",price:349.99,sizes:["XS","S","M","L","XL"],colors:["Camel","Charcoal","Oatmeal"],discount:null},
  {id:"prod_009",name:"Merino V-Neck Jumper",brand:"Uniqlo",category:"women",subcategory:"knitwear",price:79.99,sizes:["XS","S","M","L","XL"],colors:["Navy","Cream","Forest Green"],discount:null},
  {id:"prod_010",name:"Broderie Anglaise Sundress",brand:"Selected Femme",category:"women",subcategory:"dresses",price:109.99,sizes:["XS","S","M","L","XL"],colors:["White","Ivory"],discount:null},
  {id:"prod_011",name:"Tie-Front Crop Blouse",brand:"Vero Moda",category:"women",subcategory:"tops",price:44.99,sizes:["XS","S","M","L","XL"],colors:["White","Sage","Yellow"],discount:null},
  {id:"prod_012",name:"Sheer Georgette Blouse",brand:"& Other Stories",category:"women",subcategory:"blouses",price:69.99,sizes:["XS","S","M","L","XL"],colors:["Blush","Black","Ecru"],discount:null},
  {id:"prod_013",name:"High-Waist Cigarette Trousers",brand:"Reiss",category:"women",subcategory:"trousers",price:139.99,sizes:["6","8","10","12","14","16"],colors:["Black","Navy","Ivory"],discount:null},
  {id:"prod_014",name:"Asymmetric Hem Mini Skirt",brand:"Monki",category:"women",subcategory:"skirts",price:39.99,sizes:["XS","S","M","L","XL"],colors:["Black","White","Denim Blue"],discount:null},
  {id:"prod_015",name:"Halterneck Satin Jumpsuit",brand:"Weekday",category:"women",subcategory:"jumpsuits",price:89.99,sizes:["XS","S","M","L","XL"],colors:["Black","Champagne","Emerald"],discount:null},
  {id:"prod_016",name:"Double-Breasted Blazer Coat",brand:"Mango",category:"women",subcategory:"coats",price:229.99,sizes:["XS","S","M","L","XL"],colors:["Black","Camel","Houndstooth"],discount:null},
  {id:"prod_017",name:"Chunky Ribbed Turtleneck",brand:"COS",category:"women",subcategory:"knitwear",price:95.99,sizes:["XS","S","M","L","XL"],colors:["Oatmeal","Black","Rust"],discount:null},
  {id:"prod_018",name:"Smocked Bodice Midi Dress",brand:"Only",category:"women",subcategory:"dresses",price:74.99,sizes:["XS","S","M","L","XL"],colors:["Floral Pink","Blue Floral","White"],discount:null},
  {id:"prod_019",name:"Modal Off-Shoulder Top",brand:"Vero Moda",category:"women",subcategory:"tops",price:34.99,sizes:["XS","S","M","L","XL"],colors:["Black","Ivory","Dusty Rose"],discount:null},
  {id:"prod_020",name:"Puff-Sleeve Poplin Blouse",brand:"Zara",category:"women",subcategory:"blouses",price:55.99,sizes:["XS","S","M","L","XL"],colors:["White","Black","Sky Blue"],discount:null},
  {id:"prod_021",name:"Oxford Button-Down Shirt",brand:"Massimo Dutti",category:"men",subcategory:"shirts",price:89.99,sizes:["XS","S","M","L","XL"],colors:["White","Light Blue","Pink"],discount:null},
  {id:"prod_022",name:"Pique Cotton Polo Shirt",brand:"Uniqlo",category:"men",subcategory:"polos",price:39.99,sizes:["XS","S","M","L","XL"],colors:["Navy","White","Forest"],discount:null},
  {id:"prod_023",name:"Slim-Fit Wool Trousers",brand:"Reiss",category:"men",subcategory:"trousers",price:169.99,sizes:["28","30","32","34","36","38"],colors:["Charcoal","Navy","Black"],discount:null},
  {id:"prod_024",name:"Slim Selvedge Jeans",brand:"Arket",category:"men",subcategory:"jeans",price:119.99,sizes:["28","30","32","34","36"],colors:["Indigo","Black","Raw"],discount:null},
  {id:"prod_025",name:"Two-Piece Wool Suit",brand:"Massimo Dutti",category:"men",subcategory:"suits",price:349.99,sizes:["36","38","40","42","44","46"],colors:["Navy","Charcoal","Mid Grey"],discount:null},
  {id:"prod_026",name:"Quilted Leather Biker Jacket",brand:"AllSaints",category:"men",subcategory:"jackets",price:279.99,sizes:["XS","S","M","L","XL"],colors:["Black"],discount:null},
  {id:"prod_027",name:"Fleece-Lined Sweatshirt",brand:"COS",category:"men",subcategory:"sweatshirts",price:79.99,sizes:["XS","S","M","L","XL"],colors:["Ecru","Charcoal","Washed Black"],discount:null},
  {id:"prod_028",name:"Linen Bermuda Shorts",brand:"H&M",category:"men",subcategory:"shorts",price:34.99,sizes:["XS","S","M","L","XL"],colors:["Sand","Navy","Olive"],discount:null},
  {id:"prod_029",name:"Dobby-Weave Dress Shirt",brand:"Ted Baker",category:"men",subcategory:"shirts",price:99.99,sizes:["XS","S","M","L","XL"],colors:["White","Pale Blue","Lilac"],discount:null},
  {id:"prod_030",name:"Stretch Cotton Polo",brand:"Zara",category:"men",subcategory:"polos",price:45.99,sizes:["XS","S","M","L","XL"],colors:["Black","White","Burgundy"],discount:null},
  {id:"prod_031",name:"Tapered Cargo Trousers",brand:"Weekday",category:"men",subcategory:"trousers",price:74.99,sizes:["28","30","32","34","36"],colors:["Olive","Black","Stone"],discount:null},
  {id:"prod_032",name:"Straight Relaxed Jeans",brand:"H&M",category:"men",subcategory:"jeans",price:49.99,sizes:["28","30","32","34","36","38"],colors:["Light Wash","Mid Wash","Black"],discount:null},
  {id:"prod_033",name:"Linen Summer Suit",brand:"Selected Femme",category:"men",subcategory:"suits",price:299.99,sizes:["36","38","40","42","44"],colors:["Ecru","Light Blue","Sage"],discount:null},
  {id:"prod_034",name:"Waxed Cotton Field Jacket",brand:"AllSaints",category:"men",subcategory:"jackets",price:219.99,sizes:["XS","S","M","L","XL"],colors:["Olive","Navy","Black"],discount:null},
  {id:"prod_035",name:"French Terry Zip Sweatshirt",brand:"Arket",category:"men",subcategory:"sweatshirts",price:89.99,sizes:["XS","S","M","L","XL"],colors:["Washed Grey","Navy","Ecru"],discount:null},
  {id:"prod_036",name:"Swim Shorts",brand:"Mango",category:"men",subcategory:"shorts",price:39.99,sizes:["XS","S","M","L","XL"],colors:["Tropical Blue","Black","Terracotta"],discount:null},
  {id:"prod_037",name:"Linen Band-Collar Shirt",brand:"COS",category:"men",subcategory:"shirts",price:79.99,sizes:["XS","S","M","L","XL"],colors:["White","Sand","Slate"],discount:null},
  {id:"prod_038",name:"Cashmere Bomber Jacket",brand:"Reiss",category:"men",subcategory:"jackets",price:319.99,sizes:["XS","S","M","L","XL"],colors:["Camel","Black","Navy"],discount:null},
  {id:"prod_039",name:"Smock Collar Dress",brand:"H&M",category:"kids",subcategory:"dresses",price:29.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"],colors:["Pink","Blue","Yellow"],discount:null},
  {id:"prod_040",name:"Striped Long-Sleeve T-Shirt",brand:"Uniqlo",category:"kids",subcategory:"tops",price:18.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"],colors:["Navy/White","Red/White","Black/White"],discount:null},
  {id:"prod_041",name:"Jogger Trousers",brand:"Zara",category:"kids",subcategory:"trousers",price:24.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"],colors:["Grey Marl","Navy","Black"],discount:null},
  {id:"prod_042",name:"Denim Bib Overall Set",brand:"Mango",category:"kids",subcategory:"sets",price:44.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y"],colors:["Light Denim","Dark Denim"],discount:null},
  {id:"prod_043",name:"Tiered Ruffle Dress",brand:"Selected Femme",category:"kids",subcategory:"dresses",price:34.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"],colors:["Floral Pink","Floral Yellow"],discount:null},
  {id:"prod_044",name:"Graphic Sweatshirt",brand:"H&M",category:"kids",subcategory:"tops",price:22.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y","12-13Y"],colors:["Grey","Coral","Blue"],discount:null},
  {id:"prod_045",name:"Slim-Fit Chino Trousers",brand:"Zara",category:"kids",subcategory:"trousers",price:27.99,sizes:["4-5Y","6-7Y","8-9Y","10-11Y","12-13Y"],colors:["Beige","Navy","Khaki"],discount:null},
  {id:"prod_046",name:"Floral Co-Ord Set",brand:"Monki",category:"kids",subcategory:"sets",price:49.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"],colors:["Floral Lilac","Floral Green"],discount:null},
  {id:"prod_047",name:"Cable-Knit Pinafore Dress",brand:"Arket",category:"kids",subcategory:"dresses",price:59.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"],colors:["Oatmeal","Pink","Sage"],discount:null},
  {id:"prod_048",name:"Pocket Tee 2-Pack",brand:"Uniqlo",category:"kids",subcategory:"tops",price:19.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y","12-13Y"],colors:["White/Grey","Navy/White","Black/Khaki"],discount:null},
  {id:"prod_049",name:"Flare Denim Jeans",brand:"H&M",category:"kids",subcategory:"trousers",price:32.99,sizes:["4-5Y","6-7Y","8-9Y","10-11Y","12-13Y"],colors:["Light Wash","Dark Wash"],discount:null},
  {id:"prod_050",name:"Dinosaur Pyjama Set",brand:"H&M",category:"kids",subcategory:"sets",price:22.99,sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"],colors:["Blue Dino","Green Dino"],discount:null},
  {id:"prod_051",name:"Pointed-Toe Kitten Heels",brand:"Whistles",category:"shoes",subcategory:"heels",price:149.99,sizes:["36","37","38","39","40","41"],colors:["Black","Nude","Red"],discount:null},
  {id:"prod_052",name:"Chelsea Ankle Boots",brand:"AllSaints",category:"shoes",subcategory:"boots",price:199.99,sizes:["36","37","38","39","40","41","42"],colors:["Black","Tan","Dark Brown"],discount:null},
  {id:"prod_053",name:"Canvas Low-Top Trainers",brand:"Arket",category:"shoes",subcategory:"sneakers",price:69.99,sizes:["36","37","38","39","40","41","42"],colors:["White","Black","Navy"],discount:null},
  {id:"prod_054",name:"Leather Ballet Flats",brand:"Mango",category:"shoes",subcategory:"flats",price:89.99,sizes:["36","37","38","39","40","41"],colors:["Black","Nude","Burgundy"],discount:null},
  {id:"prod_055",name:"Strappy Block-Heel Sandals",brand:"Ted Baker",category:"shoes",subcategory:"sandals",price:129.99,sizes:["36","37","38","39","40","41"],colors:["Nude","Black","Silver"],discount:null},
  {id:"prod_056",name:"Suede Penny Loafers",brand:"Massimo Dutti",category:"shoes",subcategory:"loafers",price:179.99,sizes:["36","37","38","39","40","41","42"],colors:["Tan","Black","Cognac"],discount:null},
  {id:"prod_057",name:"Platform Mule Heels",brand:"Zara",category:"shoes",subcategory:"heels",price:109.99,sizes:["36","37","38","39","40","41"],colors:["Black","Ecru","Raffia"],discount:null},
  {id:"prod_058",name:"Over-the-Knee Boots",brand:"Reiss",category:"shoes",subcategory:"boots",price:249.99,sizes:["36","37","38","39","40","41"],colors:["Black","Tan"],discount:null},
  {id:"prod_059",name:"Leather Chunky Sole Trainers",brand:"COS",category:"shoes",subcategory:"sneakers",price:149.99,sizes:["40","41","42","43","44","45","46"],colors:["White","Black","Sand"],discount:null},
  {id:"prod_060",name:"Leather Derby Boots",brand:"AllSaints",category:"shoes",subcategory:"boots",price:219.99,sizes:["40","41","42","43","44","45","46"],colors:["Dark Brown","Black","Cognac"],discount:null},
  {id:"prod_061",name:"Tassel Leather Loafers",brand:"Ted Baker",category:"shoes",subcategory:"loafers",price:189.99,sizes:["40","41","42","43","44","45"],colors:["Cognac","Black","Burgundy"],discount:null},
  {id:"prod_062",name:"Mesh Running Trainers",brand:"H&M",category:"shoes",subcategory:"sneakers",price:54.99,sizes:["40","41","42","43","44","45","46"],colors:["Grey","Black","White/Blue"],discount:null},
  {id:"prod_063",name:"Suede Chelsea Boots",brand:"Whistles",category:"shoes",subcategory:"boots",price:175.99,sizes:["40","41","42","43","44","45"],colors:["Dark Brown","Navy","Black"],discount:null},
  {id:"prod_064",name:"Horsebit Leather Loafers",brand:"Massimo Dutti",category:"shoes",subcategory:"loafers",price:229.99,sizes:["40","41","42","43","44","45","46"],colors:["Black","Dark Brown","Tan"],discount:null},
  {id:"prod_065",name:"Suede Slide Sandals",brand:"Arket",category:"shoes",subcategory:"sandals",price:79.99,sizes:["40","41","42","43","44","45"],colors:["Tan","Black","White"],discount:null},
  {id:"prod_066",name:"Woven Espadrille Wedges",brand:"Mango",category:"shoes",subcategory:"sandals",price:84.99,sizes:["36","37","38","39","40","41"],colors:["Natural","Navy","White"],discount:null},
  {id:"prod_067",name:"Pointed Mule Flats",brand:"COS",category:"shoes",subcategory:"flats",price:119.99,sizes:["36","37","38","39","40","41","42"],colors:["Black","Ecru","Chocolate"],discount:null},
  {id:"prod_068",name:"Lace-Up Oxford Shoes",brand:"Reiss",category:"shoes",subcategory:"loafers",price:199.99,sizes:["40","41","42","43","44","45","46"],colors:["Black","Dark Brown","Tan"],discount:null},
  {id:"prod_069",name:"Structured Leather Tote",brand:"Whistles",category:"bags",subcategory:"totes",price:229.99,sizes:["One Size"],colors:["Tan","Black","Burgundy"],discount:null},
  {id:"prod_070",name:"Mini Leather Crossbody",brand:"& Other Stories",category:"bags",subcategory:"crossbodies",price:149.99,sizes:["One Size"],colors:["Black","Cream","Cherry Red"],discount:null},
  {id:"prod_071",name:"Satin Envelope Clutch",brand:"Ted Baker",category:"bags",subcategory:"clutches",price:89.99,sizes:["One Size"],colors:["Black","Champagne","Cobalt"],discount:null},
  {id:"prod_072",name:"Waxed Canvas Backpack",brand:"Arket",category:"bags",subcategory:"backpacks",price:179.99,sizes:["One Size"],colors:["Olive","Navy","Black"],discount:null},
  {id:"prod_073",name:"Woven Raffia Tote",brand:"Mango",category:"bags",subcategory:"totes",price:79.99,sizes:["One Size"],colors:["Natural","Black","Ecru"],discount:null},
  {id:"prod_074",name:"Quilted Chain Crossbody",brand:"Zara",category:"bags",subcategory:"crossbodies",price:119.99,sizes:["One Size"],colors:["Black","Camel","Dusty Pink"],discount:null},
  {id:"prod_075",name:"Beaded Minaudiere Clutch",brand:"Whistles",category:"bags",subcategory:"clutches",price:139.99,sizes:["One Size"],colors:["Gold","Silver","Multi"],discount:null},
  {id:"prod_076",name:"Leather City Backpack",brand:"Reiss",category:"bags",subcategory:"backpacks",price:249.99,sizes:["One Size"],colors:["Black","Dark Brown"],discount:null},
  {id:"prod_077",name:"Canvas Shopper Tote",brand:"Uniqlo",category:"bags",subcategory:"totes",price:29.99,sizes:["One Size"],colors:["Natural","Black","Navy"],discount:null},
  {id:"prod_078",name:"Pebbled Leather Saddle Bag",brand:"AllSaints",category:"bags",subcategory:"crossbodies",price:189.99,sizes:["One Size"],colors:["Tan","Black","Rust"],discount:null},
  {id:"prod_079",name:"Velvet Frame Clutch",brand:"& Other Stories",category:"bags",subcategory:"clutches",price:99.99,sizes:["One Size"],colors:["Emerald","Midnight Blue","Bordeaux"],discount:null},
  {id:"prod_080",name:"Nylon Slim Backpack",brand:"COS",category:"bags",subcategory:"backpacks",price:119.99,sizes:["One Size"],colors:["Black","Stone","Navy"],discount:null},
  {id:"prod_081",name:"Cashmere Tartan Scarf",brand:"Massimo Dutti",category:"accessories",subcategory:"scarves",price:119.99,sizes:["One Size"],colors:["Red/Black","Navy/Green","Camel/Brown"],discount:null},
  {id:"prod_082",name:"Woven Leather Belt",brand:"Reiss",category:"accessories",subcategory:"belts",price:79.99,sizes:["XS","S","M","L","XL"],colors:["Tan","Black","Cognac"],discount:null},
  {id:"prod_083",name:"Structured Fedora Hat",brand:"Whistles",category:"accessories",subcategory:"hats",price:69.99,sizes:["S/M","L/XL"],colors:["Camel","Black","Charcoal"],discount:null},
  {id:"prod_084",name:"Gold Hoop Earrings",brand:"& Other Stories",category:"accessories",subcategory:"jewellery",price:39.99,sizes:["One Size"],colors:["Gold","Silver","Rose Gold"],discount:null},
  {id:"prod_085",name:"Cat-Eye Sunglasses",brand:"Mango",category:"accessories",subcategory:"sunglasses",price:49.99,sizes:["One Size"],colors:["Tortoiseshell","Black","Transparent"],discount:null},
  {id:"prod_086",name:"Silk Twill Square Scarf",brand:"Ted Baker",category:"accessories",subcategory:"scarves",price:89.99,sizes:["One Size"],colors:["Floral Ivory","Floral Navy","Abstract"],discount:null},
  {id:"prod_087",name:"Canvas Double-Pin Belt",brand:"Arket",category:"accessories",subcategory:"belts",price:44.99,sizes:["XS","S","M","L","XL"],colors:["Khaki","Black","Navy"],discount:null},
  {id:"prod_088",name:"Merino Ribbed Beanie",brand:"COS",category:"accessories",subcategory:"hats",price:49.99,sizes:["One Size"],colors:["Ecru","Black","Camel"],discount:null},
  {id:"prod_089",name:"Pearl Station Necklace",brand:"Whistles",category:"accessories",subcategory:"jewellery",price:59.99,sizes:["One Size"],colors:["Pearl/Silver","Pearl/Gold"],discount:null},
  {id:"prod_090",name:"Aviator Sunglasses",brand:"Zara",category:"accessories",subcategory:"sunglasses",price:34.99,sizes:["One Size"],colors:["Gold/Green","Silver/Blue","Black/Smoke"],discount:null},
  {id:"prod_091",name:"Slip Satin Midi Dress",brand:"Only",category:"sale",subcategory:"dresses",price:47.99,originalPrice:79.99,discount:40,sizes:["XS","S","M","L","XL"],colors:["Champagne","Black","Emerald"]},
  {id:"prod_092",name:"Oxford Stripe Shirt",brand:"H&M",category:"sale",subcategory:"shirts",price:22.99,originalPrice:39.99,discount:43,sizes:["XS","S","M","L","XL"],colors:["Blue/White","Pink/White","Red/White"]},
  {id:"prod_093",name:"Wool Blend Camel Coat",brand:"Mango",category:"sale",subcategory:"coats",price:139.99,originalPrice:229.99,discount:39,sizes:["XS","S","M","L","XL"],colors:["Camel","Chocolate"]},
  {id:"prod_094",name:"Suede Ankle Boots",brand:"Whistles",category:"sale",subcategory:"boots",price:99.99,originalPrice:169.99,discount:41,sizes:["36","37","38","39","40","41"],colors:["Tan","Black"]},
  {id:"prod_095",name:"Leather Tote Bag",brand:"AllSaints",category:"sale",subcategory:"totes",price:109.99,originalPrice:179.99,discount:39,sizes:["One Size"],colors:["Black","Tan"]},
  {id:"prod_096",name:"Slim Stretch Jeans",brand:"Weekday",category:"sale",subcategory:"jeans",price:29.99,originalPrice:49.99,discount:40,sizes:["28","30","32","34","36"],colors:["Light Wash","Black","Dark Indigo"]},
  {id:"prod_097",name:"Merino Crew Neck Jumper",brand:"Uniqlo",category:"sale",subcategory:"knitwear",price:39.99,originalPrice:69.99,discount:43,sizes:["XS","S","M","L","XL"],colors:["Navy","Grey","Burgundy"]},
  {id:"prod_098",name:"Cashmere Wrap Scarf",brand:"Arket",category:"sale",subcategory:"scarves",price:59.99,originalPrice:99.99,discount:40,sizes:["One Size"],colors:["Camel","Grey Herringbone","Ivory"]},
  {id:"prod_099",name:"Flared Wide-Leg Jeans",brand:"Monki",category:"sale",subcategory:"jeans",price:24.99,originalPrice:44.99,discount:44,sizes:["XS","S","M","L","XL"],colors:["Mid Wash","Black","Dark Wash"]},
  {id:"prod_100",name:"Linen Relaxed Blazer",brand:"COS",category:"sale",subcategory:"jackets",price:89.99,originalPrice:149.99,discount:40,sizes:["XS","S","M","L","XL"],colors:["Sand","Navy","White"]},
  {id:"prod_101",name:"Pleated Palazzo Trousers",brand:"Selected Femme",category:"sale",subcategory:"trousers",price:44.99,originalPrice:79.99,discount:44,sizes:["XS","S","M","L","XL"],colors:["Black","Sage","Cobalt"]},
  {id:"prod_102",name:"Leather Crossbody Bag",brand:"Mango",category:"sale",subcategory:"crossbodies",price:54.99,originalPrice:99.99,discount:45,sizes:["One Size"],colors:["Black","Tan","Nude"]},
  {id:"prod_103",name:"Canvas Flatform Trainers",brand:"Vero Moda",category:"sale",subcategory:"sneakers",price:34.99,originalPrice:59.99,discount:42,sizes:["36","37","38","39","40","41"],colors:["White","Black","Ecru"]},
  {id:"prod_104",name:"Satin Bomber Jacket",brand:"Zara",category:"sale",subcategory:"jackets",price:59.99,originalPrice:99.99,discount:40,sizes:["XS","S","M","L","XL"],colors:["Black","Champagne","Cherry"]},
  {id:"prod_105",name:"Chunky Gold Chain Necklace",brand:"& Other Stories",category:"sale",subcategory:"jewellery",price:22.99,originalPrice:44.99,discount:49,sizes:["One Size"],colors:["Gold","Silver"]},
];
